id=platform.compose
layer=PLATFORM
role=UI_ADAPTER
owner=platform.compose
dependencies=feature.library.api,feature.library.ui
language=KOTLIN
externalDependencies=org.jetbrains.compose.foundation:foundation,org.jetbrains.compose.material-icons-extended,org.jetbrains.compose.material3:material3
