dependencies {
    api project(':Anilib:Kernel:Api')
    implementation project(':Anilib:Foundation')
    implementation project(':Anilib:Features:Library:Api')
    implementation project(':Anilib:Features:Source:Api')
    api project(':Anilib:Features:Reader:Api')
    implementation project(':Anilib:Features:Reader:Runtime')
    implementation project(':Anilib:Features:Reader:Ui')
}
