pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

rootProject.name = 'anilib'

include ':Anilib:Foundation'
include ':Anilib:Framework:Backup:Api'
include ':Anilib:Framework:Http:Api'
include ':Anilib:Framework:Http:Runtime'
include ':Anilib:Framework:Http:JdkRuntime'
include ':Anilib:Kernel:Api'
include ':Anilib:Kernel:Runtime'
include ':Anilib:Features:Library:Api'
include ':Anilib:Features:Library:Core'
include ':Anilib:Features:Library:Runtime'
include ':Anilib:Features:Library:Ui'
include ':Anilib:Features:Library:Bundle'
include ':Anilib:Features:LocalSource:Api'
include ':Anilib:Features:LocalSource:Runtime'
include ':Anilib:Features:LocalSource:Bundle'
include ':Anilib:Features:Source:Api'
include ':Anilib:Features:Source:Runtime'
include ':Anilib:Features:Source:Bundle'
include ':Anilib:Features:Network:Api'
include ':Anilib:Features:Network:Bundle'
include ':Anilib:Features:Settings:Api'
include ':Anilib:Features:Settings:Runtime'
include ':Anilib:Features:Settings:Ui'
include ':Anilib:Features:Settings:Bundle'
include ':Anilib:Features:Discovery:Api'
include ':Anilib:Features:Discovery:Runtime'
include ':Anilib:Features:Discovery:Ui'
include ':Anilib:Features:Discovery:Bundle'
include ':Anilib:Features:ExtensionRepository:Api'
include ':Anilib:Features:ExtensionRepository:Runtime'
include ':Anilib:Features:ExtensionRepository:Ui'
include ':Anilib:Features:ExtensionRepository:Bundle'
include ':Anilib:Features:Reader:Api'
include ':Anilib:Features:Reader:Runtime'
include ':Anilib:Features:Reader:Ui'
include ':Anilib:Features:Reader:Bundle'
include ':Anilib:Features:Downloads:Api'
include ':Anilib:Features:Downloads:Runtime'
include ':Anilib:Features:Downloads:Ui'
include ':Anilib:Features:Downloads:Bundle'
include ':Anilib:Features:Backup:Api'
include ':Anilib:Features:Backup:Runtime'
include ':Anilib:Features:Backup:Ui'
include ':Anilib:Features:Backup:Bundle'
include ':Anilib:Features:Player:Api'
include ':Anilib:Features:Player:Runtime'
include ':Anilib:Features:Player:Ui'
include ':Anilib:Features:Player:Bundle'
include ':Anilib:Features:Tracker:Api'
include ':Anilib:Features:Tracker:Runtime'
include ':Anilib:Features:Tracker:Ui'
include ':Anilib:Features:Tracker:Bundle'
include ':Anilib:Features:Updates:Api'
include ':Anilib:Features:Updates:Runtime'
include ':Anilib:Features:Updates:Ui'
include ':Anilib:Features:Updates:Bundle'
include ':Anilib:Features:CoverCache:Api'
include ':Anilib:Features:CoverCache:Runtime'
include ':Anilib:Features:CoverCache:Bundle'
include ':Anilib:Configurations:Standard'
include ':Anilib:Platforms:Compose'
include ':Anilib:Platforms:Desktop'
include ':Anilib:Platforms:Android'
include ':Anilib:Tooling:JavaQuality'
include ':Anilib:Tooling:SourcePublisher'
include ':Anilib:Tooling:ArchitectureTests'
include ':Anilib:Examples:SourceTemplate'
