id=platform.desktop-engine
layer=PLATFORM
role=APPLICATION
owner=platform.desktop-engine
dependencies=
language=JAVA
externalDependencies=de.femtopedia.dex2jar:dex-translator,net.dongliu:apk-parser,org.ow2.asm:asm,org.ow2.asm:asm-commons,org.ow2.asm:asm-tree
