id=platform.desktop-extension-host
layer=PLATFORM
role=APPLICATION
owner=platform.desktop-extension-host
dependencies=framework.concurrency.runtime
language=JAVA
externalDependencies=de.femtopedia.dex2jar:dex-translator,net.dongliu:apk-parser,org.ow2.asm:asm,org.ow2.asm:asm-commons,org.ow2.asm:asm-tree,org.jetbrains.kotlinx:kotlinx-serialization-json-jvm,org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm,com.squareup.okhttp3:okhttp,com.squareup.okhttp3:okhttp-brotli,com.squareup.okhttp3:okhttp-zstd,io.reactivex:rxjava,org.jsoup:jsoup
