id=platform.android
layer=PLATFORM
role=APPLICATION
owner=platform.android
dependencies=configuration.standard,feature.library.ui,platform.compose
language=KOTLIN
externalDependencies=androidx.activity:activity-compose
