id=platform.android
layer=PLATFORM
role=APPLICATION
owner=platform.android
dependencies=framework.http.runtime,configuration.standard,feature.discovery.ui,feature.library.ui,feature.reader.ui,feature.player.ui,feature.downloads.ui,feature.backup.ui,feature.tracker.ui,feature.updates.api,feature.updates.ui,platform.compose
language=KOTLIN
externalDependencies=androidx.activity:activity-compose
