id=platform.android
layer=PLATFORM
role=APPLICATION
owner=platform.android
dependencies=framework.http.runtime,configuration.standard,feature.discovery.ui,feature.library.ui,platform.compose
language=KOTLIN
externalDependencies=androidx.activity:activity-compose
