id=feature.extension-repository.ui
layer=FEATURE
role=UI
owner=feature.extension-repository
dependencies=foundation,framework.localization.api,kernel.api,feature.extension-repository.api,feature.settings.api
