package=fr.vriege.anilib.example.source
versionCode=1
api=1.6
module=fr.vriege.anilib.example.source
source.count=1
source.0.id=example.catalogue
source.0.component=extension.example.catalogue
source.0.name=Anilib Example Catalogue
source.0.factory=fr.vriege.anilib.example.source.ExampleSourceFactory
source.0.origins=
