plugins {
    id 'application'
}

dependencies {
    implementation project(':Anilib:Tooling:JavaQuality')
    implementation project(':Anilib:Foundation')
    implementation project(':Anilib:Kernel:Api')
    implementation project(':Anilib:Kernel:Runtime')
    implementation project(':Anilib:Configurations:Standard')
    implementation project(':Anilib:Features:Discovery:Api')
    implementation project(':Anilib:Features:Discovery:Ui')
    implementation project(':Anilib:Features:CoverCache:Api')
    implementation project(':Anilib:Features:CoverCache:Runtime')
    implementation project(':Anilib:Features:CoverCache:Bundle')
    implementation project(':Anilib:Features:Library:Api')
    implementation project(':Anilib:Features:Library:Core')
    implementation project(':Anilib:Features:Library:Runtime')
    implementation project(':Anilib:Features:Library:Ui')
    implementation project(':Anilib:Features:LocalSource:Api')
    implementation project(':Anilib:Features:LocalSource:Runtime')
    implementation project(':Anilib:Features:Source:Api')
    implementation project(':Anilib:Features:Source:Bundle')
    implementation project(':Anilib:Framework:Http:Api')
    implementation project(':Anilib:Framework:Http:Runtime')
    implementation project(':Anilib:Framework:Http:JdkRuntime')
    implementation project(':Anilib:Features:Network:Api')
    implementation project(':Anilib:Features:Network:Bundle')
    implementation project(':Anilib:Features:Reader:Api')
    implementation project(':Anilib:Features:Reader:Runtime')
    implementation project(':Anilib:Features:Reader:Ui')
}

application {
    mainModule = 'fr.vriege.anilib.tooling.archtests'
    mainClass = 'fr.vriege.anilib.tooling.archtests.ArchitectureTestMain'
}
