dependencies {
    implementation project(':Anilib:Foundation')
    implementation project(':Anilib:Framework:Backup:Api')
    implementation project(':Anilib:Kernel:Api')
    implementation project(':Anilib:Features:Library:Api')
    implementation project(':Anilib:Features:Settings:Api')
    implementation project(':Anilib:Features:Source:Api')
    api project(':Anilib:Features:Player:Api')
    implementation project(':Anilib:Features:Player:Runtime')
    implementation project(':Anilib:Features:Player:Ui')
}
