id=platform.android.app
layer=PLATFORM
role=APPLICATION
owner=platform.android
dependencies=feature.library.ui,platform.android,platform.compose
language=KOTLIN
externalDependencies=androidx.activity:activity-compose
