id=platform.desktop
layer=PLATFORM
role=APPLICATION
owner=platform.desktop
dependencies=framework.http.jdk-runtime,configuration.standard,feature.cover-cache.bundle,feature.discovery.ui,feature.extension-repository.ui,feature.network.api,feature.settings.ui,feature.library.ui,feature.reader.ui,feature.player.ui,feature.downloads.ui,feature.backup.ui,feature.tracker.ui,feature.updates.api,feature.updates.ui,feature.application-update.ui,kernel.api,platform.compose
language=JAVA_KOTLIN
externalDependencies=org.jetbrains.compose:compose-desktop
