id=platform.desktop
layer=PLATFORM
role=APPLICATION
owner=platform.desktop
dependencies=framework.http.jdk-runtime,configuration.standard,feature.cover-cache.bundle,feature.library.ui,kernel.api,platform.compose
language=JAVA_KOTLIN
externalDependencies=org.jetbrains.compose:compose-desktop
