id=platform.desktop
layer=PLATFORM
role=APPLICATION
owner=platform.desktop
dependencies=foundation,framework.concurrency.runtime,framework.http.api,framework.http.jdk-runtime,configuration.standard,feature.cover-cache.bundle,feature.library.api,feature.discovery.ui,feature.extension-repository.api,feature.extension-repository.runtime,feature.extension-repository.ui,feature.network.api,feature.settings.api,feature.settings.ui,feature.library.ui,feature.reader.ui,feature.player.api,feature.player.ui,feature.source.api,feature.downloads.api,feature.downloads.ui,feature.backup.ui,feature.tracker.ui,feature.updates.api,feature.updates.ui,feature.application-update.api,feature.application-update.ui,kernel.api,platform.compose,platform.desktop-extension-host
language=JAVA_KOTLIN
externalDependencies=org.jetbrains.compose:compose-desktop,org.jetbrains.compose.ui:ui-test,org.jetbrains.kotlin:kotlin-test,io.github.kevinnzou:compose-webview-multiplatform
