dependencies {
    api project(':Anilib:Framework:Http:Api')
    implementation project(':Anilib:Framework:Http:Runtime')
    api project(':Anilib:Kernel:Api')
    implementation project(':Anilib:Kernel:Runtime')
    implementation project(':Anilib:Features:Library:Bundle')
    implementation project(':Anilib:Features:Source:Bundle')
    implementation project(':Anilib:Features:LocalSource:Bundle')
    implementation project(':Anilib:Features:Network:Bundle')
    implementation project(':Anilib:Features:Discovery:Bundle')
    implementation project(':Anilib:Features:Reader:Bundle')
    implementation project(':Anilib:Features:Downloads:Bundle')
    api project(':Anilib:Features:Player:Api')
    implementation project(':Anilib:Features:Player:Bundle')
    implementation project(':Anilib:Features:Backup:Bundle')
}
