id=configuration.standard
layer=CONFIGURATION
role=CONFIGURATION
owner=product.standard
dependencies=framework.http.api,framework.http.runtime,kernel.api,kernel.runtime,feature.library.bundle,feature.source.bundle,feature.local-source.bundle,feature.network.api,feature.network.bundle,feature.settings.bundle,feature.discovery.bundle,feature.extension-repository.bundle,feature.reader.bundle,feature.downloads.bundle,feature.player.api,feature.player.bundle,feature.tracker.api,feature.tracker.bundle,feature.tracker.anilist,feature.updates.api,feature.updates.bundle,feature.application-update.bundle,feature.backup.bundle
