dependencies {
    api project(':Anilib:Features:Downloads:Api')
    api project(':Anilib:Kernel:Api')
    implementation project(':Anilib:Foundation')
    implementation project(':Anilib:Features:Library:Api')
    implementation project(':Anilib:Features:Network:Api')
    implementation project(':Anilib:Features:Reader:Api')
    implementation project(':Anilib:Features:Settings:Api')
    implementation project(':Anilib:Features:Source:Api')
    implementation project(':Anilib:Features:Downloads:Runtime')
    implementation project(':Anilib:Features:Downloads:Ui')
}
