name: Publish source template

on:
  workflow_dispatch:
  push:
    tags:
      - 'source-template-v*'

jobs:
  publish:
    uses: ./.github/workflows/source-repository-publish.yml
    with:
      bundle-task: :Anilib:Examples:SourceTemplate:jar
      package-configuration: Anilib/Examples/SourceTemplate/source-publisher.properties
      publication-branch: repo
    secrets:
      SOURCE_PUBLISHER_PRIVATE_KEY: ${{ secrets.SOURCE_PUBLISHER_PRIVATE_KEY }}
